// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_oSyzpXa1F0hNeUN_4bweEuxe79flQgM',
    appId: '1:541122942267:web:962a5d19a75e8dd3d7531e',
    messagingSenderId: '541122942267',
    projectId: 'flutter-fchat',
    authDomain: 'flutter-fchat.firebaseapp.com',
    storageBucket: 'flutter-fchat.firebasestorage.app',
    measurementId: 'G-BSC7MFP8XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp8HH2V_td3rexAH5ZMKadTE_p__OxSUQ',
    appId: '1:541122942267:android:29e70fb567a64991d7531e',
    messagingSenderId: '541122942267',
    projectId: 'flutter-fchat',
    storageBucket: 'flutter-fchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiv3QF4xPbdaCCqQQ-0AFujKqCIIXzOxg',
    appId: '1:541122942267:ios:48c32339b21e2094d7531e',
    messagingSenderId: '541122942267',
    projectId: 'flutter-fchat',
    storageBucket: 'flutter-fchat.firebasestorage.app',
    iosBundleId: 'com.example.flutterFchat',
  );

}